import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/providers/providers";
import { Topbar } from "@/components/layout/Topbar";
import { ContextProvider } from "@/providers/contextProvider";
import { ToggleSidebar } from "@/components/ui/ToggleSidebar";
import { Sidebar } from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${inter.className} flex relative`}>
        <Providers>
          <ContextProvider>
            <Topbar />
            <ToggleSidebar>
              <Sidebar/>
            </ToggleSidebar>
            <main>
              {children}
            </main>
          </ContextProvider>
        </Providers>
      </body>
    </html>
  );
}
